# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(702, 462)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.weekly_explorer = QtWidgets.QTreeWidget(self.centralwidget)
        self.weekly_explorer.setEnabled(True)
        self.weekly_explorer.setGeometry(QtCore.QRect(0, 0, 471, 411))
        self.weekly_explorer.setObjectName("weekly_explorer")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(500, 220, 181, 51))
        self.loadButton.setObjectName("loadButton")
        self.addProjectButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProjectButton.setGeometry(QtCore.QRect(500, 80, 181, 51))
        self.addProjectButton.setObjectName("addProjectButton")
        self.newDateButton = QtWidgets.QPushButton(self.centralwidget)
        self.newDateButton.setGeometry(QtCore.QRect(500, 10, 181, 51))
        self.newDateButton.setObjectName("newDateButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(500, 290, 181, 51))
        self.saveButton.setObjectName("saveButton")
        self.removeItemButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeItemButton.setGeometry(QtCore.QRect(500, 150, 181, 51))
        self.removeItemButton.setObjectName("removeItemButton")
        self.getOutputButton = QtWidgets.QPushButton(self.centralwidget)
        self.getOutputButton.setGeometry(QtCore.QRect(500, 360, 181, 51))
        self.getOutputButton.setObjectName("getOutputButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Load"))
        self.addProjectButton.setText(_translate("MainWindow", "add project to date"))
        self.newDateButton.setText(_translate("MainWindow", "add new date"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.removeItemButton.setText(_translate("MainWindow", "remove item"))
        self.getOutputButton.setText(_translate("MainWindow", "get output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
